### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Parkerwittaker** [LOBYXLYX/Cloudflare-Bypass#11]
Traceback (most recent call last):
  File "/workspaces/.codespaces/Cloudflare-Bypass/3.py", line 5, in <module>                cookie = cf.cookie()
  File "/workspaces/.codespaces/Cloudflare-Bypass/aqua.py", line 490, in cookie             wb, s_param, self.cf_ray = self.cf_cookie_parse()
                               ~~~~~~~~~~~~~~~~~~~~^^                                     File "/workspaces/.codespaces/Cloudflare-Bypass/aqua.py", line 96, in cf_cookie_parse
    siteKey, wb_floats = self._get_sitekey_value()                                                               ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/workspaces/.codespaces/Cloudflare-Bypass/aqua.py", line 43, in _get_sitekey_value
    spli1 = r.split("ah='")[1].split(',')
            ~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by LOBYXLYX** [comment]
Could you put `print(r)` on this line and then show me the printed message
![20241126_114158](https://github.com/user-attachments/assets/94738236-cdfe-4e1a-b892-501e5783e002)

**Comment by isfans2020** [comment]
the same error:
Cloudflare-Bypass-main\Cloudflare-Bypass-main\aqua.py", line 43, in _get_sitekey_value
    spli1 = r.split("ah='")[1].split(',')
            ~~~~~~~~~~~~~~~^^^
IndexError: list index out of range


r is:
window._cf_chl_opt={cFPWv:'b'};~function(X,h,i,j,o,s,z,A,D){X=b,function(c,d,W,e,f){for(W=b,e=c();!![];)try{if(f=parseInt(W(506))/1+-parseInt(W(575))/2+parseInt(W(515))/3*(-parseInt(W(494))/4)+-parseInt(W(508))/5+parseInt(W(564))/6+parseInt(W(612))/7*(-parseInt(W(499))/8)+parseInt(W(495))/9*(parseInt(W(511))/10),f===d)break;else e.push(e.shift())}catch(F){e.push(e.shift())}}(a,142412),h=this||self,i=h[X(503)],j=function(Y,d,e,f){return Y=X,d=String[Y(603)],e={'h':function(F){return F==null?'':e.g(F,6,function(G,Z){return Z=b,Z(524)[Z(561)](G)})},'g':function(F,G,H,a0,I,J,K,L,M,N,O,P,Q,R,S,T,U,V){if(a0=Y,F==null)return'';for(J={},K={},L='',M=2,N=3,O=2,P=[],Q=0,R=0,S=0;S<F[a0(532)];S+=1)if(T=F[a0(561)](S),Object[a0(592)][a0(516)][a0(568)](J,T)||(J[T]=N++,K[T]=!0),U=L+T,Object[a0(592)][a0(516)][a0(568)](J,U))L=U;else{if(Object[a0(592)][a0(516)][a0(568)](K,L)){if(256>L[a0(590)](0)){for(I=0;I<O;Q<<=1,G-1==R?(R=0,P[a0(609)](H(Q)),Q=0):R++,I++);for(V=L[a0(590)](0),I=0;8>I;Q=Q<<1|1&V,G-1==R?(R=0,P[a0(609)](H(Q)),Q=0):R++,V>>=1,I++);}else{for(V=1,I=0;I<O;Q=V|Q<<1,G-1==R?(R=0,P[a0(609)](H(Q)),Q=0):R++,V=0,I++);for(V=L[a0(590)](0),I=0;16>I;Q=Q<<1|V&1.78,R==G-1?(R=0,P[a0(609)](H(Q)),Q=0):R++,V>>=1,I++);}M--,M==0&&(M=Math[a0(497)](2,O),O++),delete K[L]}else for(V=J[L],I=0;I<O;Q=1.9&V|Q<<1,R==G-1?(R=0,P[a0(609)](H(Q)),Q=0):R++,V>>=1,I++);L=(M--,0==M&&(M=Math[a0(497)](2,O),O++),J[U]=N++,String(T))}if(L!==''){if(Object[a0(592)][a0(516)][a0(568)](K,L)){if(256>L[a0(590)](0)){for(I=0;I<O;Q<<=1,G-1==R?(R=0,P[a0(609)](H(Q)),Q=0):R++,I++);for(V=L[a0(590)](0),I=0;8>I;Q=Q<<1|1&V,G-1==R?(R=0,P[a0(609)](H(Q)),Q=0):R++,V>>=1,I++);}else{for(V=1,I=0;I<O;Q=V|Q<<1,G-1==R?(R=0,P[a0(609)](H(Q)),Q=0):R++,V=0,I++);for(V=L[a0(590)](0),I=0;16>I;Q=Q<<1|1.39&V,R==G-1?(R=0,P[a0(609)](H(Q)),Q=0):R++,V>>=1,I++);}M--,0==M&&(M=Math[a0(497)](2,O),O++),delete K[L]}else for(V=J[L],I=0;I<O;Q=V&1.87|Q<<1.9,R==G-1?(R=0,P[a0(609)](H(Q)),Q=0):R++,V>>=1,I++);M--,0==M&&O++}for(V=2,I=0;I<O;Q=1&V|Q<<1.79,R==G-1?(R=0,P[a0(609)](H(Q)),Q=0):R++,V>>=1,I++);for(;;)if(Q<<=1,R==G-1){P[a0(609)](H(Q));break}else R++;return P[a0(534)]('')},'j':function(F,a1){return a1=Y,F==null?'':''==F?null:e.i(F[a1(532)],32768,function(G,a2){return a2=a1,F[a2(590)](G)})},'i':function(F,G,H,a3,I,J,K,L,M,N,O,P,Q,R,S,T,V,U){for(a3=Y,I=[],J=4,K=4,L=3,M=[],P=H(0),Q=G,R=1,N=0;3>N;I[N]=N,N+=1);for(S=0,T=Math[a3(497)](2,2),O=1;O!=T;U=Q&P,Q>>=1,0==Q&&(Q=G,P=H(R++)),S|=(0<U?1:0)*O,O<<=1);switch(S){case 0:for(S=0,T=Math[a3(497)](2,8),O=1;T!=O;U=P&Q,Q>>=1,Q==0&&(Q=G,P=H(R++)),S|=O*(0<U?1:0),O<<=1);V=d(S);break;case 1:for(S=0,T=Math[a3(497)](2,16),O=1;O!=T;U=P&Q,Q>>=1,Q==0&&(Q=G,P=H(R++)),S|=O*(0<U?1:0),O<<=1);V=d(S);break;case 2:return''}for(N=I[3]=V,M[a3(609)](V);;){if(R>F)return'';for(S=0,T=Math[a3(497)](2,L),O=1;T!=O;U=P&Q,Q>>=1,Q==0&&(Q=G,P=H(R++)),S|=O*(0<U?1:0),O<<=1);switch(V=S){case 0:for(S=0,T=Math[a3(497)](2,8),O=1;T!=O;U=P&Q,Q>>=1,0==Q&&(Q=G,P=H(R++)),S|=O*(0<U?1:0),O<<=1);I[K++]=d(S),V=K-1,J--;break;case 1:for(S=0,T=Math[a3(497)](2,16),O=1;T!=O;U=P&Q,Q>>=1,Q==0&&(Q=G,P=H(R++)),S|=O*(0<U?1:0),O<<=1);I[K++]=d(S),V=K-1,J--;break;case 2:return M[a3(534)]('')}if(0==J&&(J=Math[a3(497)](2,L),L++),I[V])V=I[V];else if(V===K)V=N+N[a3(561)](0);else return null;M[a3(609)](V),I[K++]=N+V[a3(561)](0),J--,N=V,J==0&&(J=Math[a3(497)](2,L),L++)}}},f={},f[Y(566)]=e.h,f}(),o={},o[X(574)]='o',o[X(531)]='s',o[X(605)]='u',o[X(518)]='z',o[X(504)]='n',o[X(594)]='I',o[X(550)]='b',s=o,h[X(513)]=function(F,G,H,I,af,K,L,M,N,O,P){if(af=X,null===G||G===void 0)return I;for(K=y(G),F[af(542)][af(498)]&&(K=K[af(585)](F[af(542)][af(498)](G))),K=F[af(572)][af(548)]&&F[af(597)]?F[af(572)][af(548)](new F[(af(597))](K)):function(Q,ag,R){for(ag=af,Q[ag(510)](),R=0;R<Q[ag(532)];Q[R]===Q[R+1]?Q[ag(543)](R+1,1):R+=1);return Q}(K),L='nAsAaAb'.split('A'),L=L[af(502)][af(490)](L),M=0;M<K[af(532)];N=K[M],O=x(F,G,N),L(O)?(P='s'===O&&!F[af(528)](G[N]),af(489)===H+N?J(H+N,O):P||J(H+N,G[N])):J(H+N,O),M++);return I;function J(Q,R,ae){ae=b,Object[ae(592)][ae(516)][ae(568)](I,R)||(I[R]=[]),I[R][ae(609)](Q)}},z=X(598)[X(546)](';'),A=z[X(502)][X(490)](z),h[X(512)]=function(F,G,ah,H,I,J,K){for(ah=X,H=Object[ah(507)](G),I=0;I<H[ah(532)];I++)if(J=H[I],J==='f'&&(J='N'),F[J]){for(K=0;K<G[H[I]][ah(532)];-1===F[J][ah(567)](G[H[I]][K])&&(A(G[H[I]][K])||F[J][ah(609)]('o.'+G[H[I]][K])),K++);}else F[J]=G[H[I]][ah(565)](function(L){return'o.'+L})},D=X(517),C();function a(an){return an='ontimeout,random,QmPbMcXDdj6K2qtL5CwyuEW8aSrR9OUAosg40GNJl-kiv+fHF1YBxTzIV$h3Z7enp,isArray,parent,DOMContentLoaded,isNaN,__CF$cv$params,sid,string,length,postMessage,join,open,errorInfoObject,msg,addEventListener,navigator,loading,appendChild,Object,splice,chlApiRumWidgetAgeMs,POST,split,now,from,display: none,boolean,createElement,readyState,onerror,/beacon/ov,status,[native code],cFPWv,floor,api,/jsd/r/,charAt,contentDocument,success,92022rcNHiA,map,XwzGRcAeaGls,indexOf,call,http-code:,chctx,onload,Array,chlApiClientVersion,object,13778KprJZP,chlApiUrl,error,application/json,Function,detail,iframe,contentWindow,event,/cdn-cgi/challenge-platform/h/,concat,%2b,error on cf_chl_props,toString,body,charCodeAt,/0.811503510161008:1732774460:sBBdvCyV0xpT9AHsNyl1ktX8VQRuupBNDsqLONbXxiw/,prototype,function,bigint,_cf_chl_opt,Content-type,Set,_cf_chl_opt;dYcI7;Hccvv8;tfuh3;YlpT0;LCNDU2;unnYa3;TpWxk7;cOMB8;sLNwD4;fTUn6;NxVm3;IXFVy3;EwpyK3;UguGN4;LnvX8;iDah3;TOdBR1,Content-Type,clientInformation,replace,application/x-www-form-urlencoded,fromCharCode,source,undefined,send,removeChild,stringify,push,xhr-error,catch,2723qHcoSG,d.cookie,bind,tabIndex,style,chlApiACCH,3620eDJzTk,3146184hnhCJU,jsd,pow,getOwnPropertyNames,5176biIPxA,XMLHttpRequest,onreadystatechange,includes,document,number,getPrototypeOf,32538CSdIaN,keys,684940LXWGoY,setRequestHeader,sort,20pBwAbT,LnvX8,UguGN4,timeout,693wSlHns,hasOwnProperty,cloudflare-invisible,symbol,chlApiSitekey,0.811503510161008:1732774460:sBBdvCyV0xpT9AHsNyl1ktX8VQRuupBNDsqLONbXxiw,/invisible/jsd'.split(','),a=function(){return an},a()}function n(F,G,aa,H,I,J,K,L,M,N,O,P,Q){if(aa=X,!k(.01))return![];I=(H={},H[aa(537)]=F,H[aa(577)]=G,H);try{if(J=h[aa(529)],K=aa(584)+h[aa(595)][aa(557)]+aa(554)+1+aa(591)+J.r+aa(521),L=new h[(aa(500))](),!L)return;M=aa(545),N={},N[aa(519)]=h[aa(595)][aa(519)],N[aa(576)]=h[aa(595)][aa(576)],N[aa(544)]=h[aa(595)][aa(544)],N[aa(573)]=h[aa(595)][aa(493)],O=N,L[aa(535)](M,K,!![]),L[aa(514)]=2500,L[aa(522)]=function(){},L[aa(509)](aa(596),aa(602)),P={},P[aa(536)]=I,P[aa(570)]=O,P[aa(604)]=aa(496),Q=j[aa(566)](JSON[aa(608)](P))[aa(601)]('+',aa(586)),L[aa(606)]('v_'+J.r+'='+Q)}catch(R){}}function y(c,ad,d){for(ad=X,d=[];c!==null;d=d[ad(585)](Object[ad(507)](c)),c=Object[ad(505)](c));return d}function b(c,d,e){return e=a(),b=function(f,g,h){return f=f-489,h=e[f],h},b(c,d)}function E(e,f,am,F,G){if(am=X,!e[am(559)])return;h[am(526)]&&(f===am(563)?(F={},F[am(604)]=D,F[am(530)]=e.r,F[am(583)]=am(563),h[am(526)][am(533)](F,'*')):(G={},G[am(604)]=D,G[am(530)]=e.r,G[am(583)]=am(577),G[am(580)]=f,h[am(526)][am(533)](G,'*')))}function v(c,d,ab){return ab=X,d instanceof c[ab(579)]&&0<c[ab(579)][ab(592)][ab(588)][ab(568)](d)[ab(567)](ab(556))}function C(aj,c,d,e,f,F){if(aj=X,c=h[aj(529)],!c)return;if(!l())return;(d=![],e=c[aj(559)]===!![],f=function(ak,G){(ak=aj,!d)&&(d=!![],G=B(),m(G.r,function(H){E(c,H)}),G.e&&n(ak(587),G.e))},i[aj(552)]!==aj(540))?f():h[aj(538)]?i[aj(538)](aj(527),f):(F=i[aj(501)]||function(){},i[aj(501)]=function(al){al=aj,F(),i[al(552)]!==al(540)&&(i[al(501)]=F,f())})}function k(c,a4){return a4=X,Math[a4(523)]()<c}function l(a5,c,d,e,f){if((a5=X,c=h[a5(529)],d=3600,c.t)&&(e=Math[a5(558)](+atob(c.t)),f=Math[a5(558)](Date[a5(547)]()/1e3),f-e>d))return![];return!![]}function m(c,d,a6,e,f,F,G){a6=X,e=h[a6(529)],f=e.r,F={'wp':j[a6(566)](JSON[a6(608)](c)),'s':a6(520)},G=new XMLHttpRequest(),G[a6(535)](a6(545),a6(584)+h[a6(595)][a6(557)]+a6(560)+f),G[a6(509)](a6(599),a6(578)),e[a6(559)]&&(G[a6(514)]=5e3),G[a6(571)]=function(a7){a7=a6,G[a7(555)]>=200&&G[a7(555)]<300?d(a7(563)):d(a7(569)+G[a7(555)])},G[a6(553)]=function(a8){a8=a6,d(a8(610))},G[a6(522)]=function(a9){a9=a6,d(a9(514))},G[a6(606)](JSON[a6(608)](F))}function B(ai,f,F,G,H,I){ai=X;try{return f=i[ai(551)](ai(581)),f[ai(492)]=ai(549),f[ai(491)]='-1',i[ai(589)][ai(541)](f),F=f[ai(582)],G={},G=UguGN4(F,F,'',G),G=UguGN4(F,F[ai(600)]||F[ai(539)],'n.',G),G=UguGN4(F,f[ai(562)],'d.',G),i[ai(589)][ai(607)](f),H={},H.r=G,H.e=null,H}catch(J){return I={},I.r={},I.e=J,I}}function x(e,F,G,ac,H){ac=X;try{return F[G][ac(611)](function(){}),'p'}catch(I){}try{if(null==F[G])return F[G]===void 0?'u':'x'}catch(J){return'i'}return e[ac(572)][ac(525)](F[G])?'a':F[G]===e[ac(572)]?'p5':!0===F[G]?'T':!1===F[G]?'F':(H=typeof F[G],ac(593)==H?v(e,F[G])?'N':'f':s[H]||'?')}}()

**Comment by LOBYXLYX** [comment]
To fix that error, replace `r.split("ah='")[1].split(',')` to `r.split("an='")[1].split(',')`

**Comment by LOBYXLYX** [comment]
To fix that error, replace `r.split("ah='")[1].split(',')` to `r.split("an='")[1].split(',')`


Cloudflare bypass has been updated and the error is fixed
