### ISSUE TITLE
why not success

### ISSUE THREAD

**Issue by shuaibibobo** [LOBYXLYX/Cloudflare-Bypass#15]
request payload: v_8f0ecc5cffcb3def=5USJGJIJjJ6JPJ8kv4kvzuhzhCVLhVvhuwCThjwvmkvwTfvt7JT0Ez70GKUhBv2uITvYIJvHpvVsrvLq....
cloudflare response: {"err":100040}.... 
Traceback (most recent call last):
  File "d:\newcode\test\Cloudflare-Bypass-main\aqua.py", line 614, in <module>
    cf.solve_turnstile()
  File "d:\newcode\test\Cloudflare-Bypass-main\aqua.py", line 548, in solve_turnstile
    challenge_result, _eval = cf_turnstile.solve_flow_ov1(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newcode\test\Cloudflare-Bypass-main\aqua.py", line 353, in solve_flow_ov1
    _window_decrypted = self.vm_automation.send_ov1_request(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\newcode\test\Cloudflare-Bypass-main\orchestrate_full_reverse.py", line 243, in send_ov1_request
    raise TypeError(f'Cloudflare Challenge Failed ({result["encrypted"]})')
TypeError: Cloudflare Challenge Failed ({"err":100040})

**Comment by LOBYXLYX** [comment]
Do you always get {err: 100040}? Or does it only appear sometimes?

**Comment by LOBYXLYX** [comment]
Okay, let me figure out how to fix these errors
