### ISSUE TITLE
Hello, may I ask what is the version of Node.js

### ISSUE THREAD

**Issue by qiaolang** [LOBYXLYX/Cloudflare-Bypass#18]
Hello, may I ask what is the version of Node.js

**Comment by LOBYXLYX** [comment]
I am using version 22.8.0

**Comment by qiaolang** [comment]
What is the Python version? I am using Python 3.8. Running error
The error is as follows:
decrypted: window._=function(){};  window._[0]='a';  window._[1]='b';     var _cf_chl_ctx = arguments[0]
Traceback (most recent call last):
File "aqua.py", line 614, in <module>
cf.solve_turnstile()
File "aqua.py", line 548, in solve_turnstile
challenge_result, _eval = cf_turnstile.solve_flow_ov1(
File "aqua.py", line 360, in solve_flow_ov1
eval_result = self.vm_automation.evaluate(
File "C:\Users\Administrator\Desktop\Cloudflare-Bypass-main\orchestrate_full_reverse.py", line 511, in evaluate
_parse_window_eval()
File "C:\Users\Administrator\Desktop\Cloudflare-Bypass-main\orchestrate_full_reverse.py", line 450, in _parse_window_eval
t = code.split(".screen.orientation,'so.',")[1].split('var d={};d=')[1].split('(')[0]
IndexError: list index out of range

**Comment by LOBYXLYX** [comment]
Turnstile solver is not finished and may contain bugs
