### ISSUE TITLE
 def _get_s_parameter(self) -> tuple[typing.Optional[str], str]: TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by junai-py** [LOBYXLYX/Cloudflare-Bypass#6]
im trying your repo 
getting this following exception 
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/arunjunai/PycharmProjects/bot_blocking/Cloudflare-Bypass-main/aqua.py", line 16, in <module>
    class CF_MetaData:
  File "/home/arunjunai/PycharmProjects/bot_blocking/Cloudflare-Bypass-main/aqua.py", line 24, in CF_MetaData
    def _get_s_parameter(self) -> tuple[typing.Optional[str], str]:
TypeError: 'type' object is not subscriptable

**Comment by LOBYXLYX** [comment]
Change

`def _get_s_parameter(self) -> tuple[typing.Optional[str], str]:`

To:

`def _get_s_parameter(self):`

And if you get another similar one, do the same. And what version of Python do you have?
